[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  PUBLIC_USE_NETLIFY_FORMS = "true"

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/thank-you"
  to = "/index.html#contact"
  status = 200


